
#FROM microsoft/dotnet:aspnetcore-runtime
FROM microsoft/dotnet:2.1-runtime-deps-alpine
WORKDIR /root/  
COPY linux-x64 .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000/tcp
CMD ["StankinsAliveMonitor"]  
